services:
  db:
    image: postgres:16
    container_name: ares_db
    restart: always
    environment:
      POSTGRES_USER: ares_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ares_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ares_user -d ares_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ares_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ares.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
